✨ Add data object support
process-engine/bpmn-studio pull request #2070
Opened 2020-08-19 14:01 UTC by alexanderkasten

## Changes

1. Update AtlasEngine to apply DataObjects Feature
2. Add PropertyPanel sections for DataObjects elements
3. Add DataObjects help text

## Issues

PR: #NumberOfThisPR

## How to test the changes

- checkout
- npm ci
- npm run electron-start-dev
- create new diagram with data object element
- add association from and to data object element
- look at the property panel
- read the help text
- use it
- test it

2020-08-19 14:22 UTC, ElRaptorus requested changes
Funktional siehts gut aus. 

Würde beim "Data Output Associations" Property Panel auch noch den gleichen Hinweis wie bei der DataInputAssociation hinterlegen ("This is a Data Output Association from ...."), samt einem Link zum Data Object Hilfstext.

2020-08-19 14:22 UTC, ElRaptorus commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/data-objects.html
> +      <p class="information-text">Data Objects present a simple way of storing data for a process instance globally. <a class="data-objects-enlarge-link" click.delegate="showDataObjectsHelpModal()">C
```suggestion
      <p class="information-text">Data Objects present a simple way of storing data for a process instance globally. <a class="data-objects-enlarge-link" click.delegate="showDataObjectsHelpModal()">Click here for a usage example...</a></p>
```

2020-08-19 14:22 UTC, ElRaptorus commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/data-objects.html
> +      <i class="fas fa-info-circle feedback-modal__help-icon" title="Help: How to use data objects" click.delegate="showDataObjectsHelpModal()"></i>
```suggestion
      <i class="fas fa-info-circle feedback-modal__help-icon" title="Help: How to use Data Objects" click.delegate="showDataObjectsHelpModal()"></i>
```

2020-08-19 14:22 UTC, ElRaptorus commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/input-association/input-association.html
> +      <i class="fas fa-info-circle feedback-modal__help-icon" title="Help: How to use data objects" click.delegate="showDataObjectsHelpModal()"></i>
```suggestion
      <i class="fas fa-info-circle feedback-modal__help-icon" title="Help: How to use Data Objects" click.delegate="showDataObjectsHelpModal()"></i>
```

2020-08-19 14:22 UTC, ElRaptorus commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/input-association/input-association.html
> +      <p class="information-text">This is an input association from a data object to another flow node (event or task). <a class="input-association-enlarge-link" click.delegate="showDataObjectsHelpMo
```suggestion
      <p class="information-text">This is a Data Input Association from a Data Object to a Flow Node (event or task). <a class="input-association-enlarge-link" click.delegate="showDataObjectsHelpModal()">Click here for more information...</a> </p>
```

2020-08-19 14:22 UTC, ElRaptorus commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/output-association/output-association.html
> +      <i class="fas fa-info-circle feedback-modal__help-icon" title="Help: How to use data objects" click.delegate="showDataObjectsHelpModal()"></i>
```suggestion
      <i class="fas fa-info-circle feedback-modal__help-icon" title="Help: How to use Data Objects" click.delegate="showDataObjectsHelpModal()"></i>
```

2020-08-19 14:22 UTC, ElRaptorus commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/input-association/input-association.ts
> +  public path: string = '/sections/data-objects/input-association/input-association';
Die Associations nennen sich "DataInputAssociation", bzw. "DataOutputAssociation". Sollte man auch hier bei der internen Verwendung entsprechend ausschreiben.

```suggestion
  public path: string = '/sections/data-objects/input-association/data-input-association';
```

2020-08-19 14:22 UTC, ElRaptorus commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/output-association/output-association.ts
> +  public path: string = '/sections/data-objects/output-association/output-association';
s.o.

```suggestion
  public path: string = '/sections/data-objects/output-association/data-output-association';
```

2020-08-19 14:22 UTC, ElRaptorus commented on package.json
> +    "@atlas-engine/fullstack_server": "10.1.0-feature-cdd828-kdyne3xz",
```suggestion
    "@atlas-engine/fullstack_server": "10.1.0-beta.2",
```

2020-08-19 14:22 UTC, ElRaptorus commented on src/services/help-modal-service/help-texts/data-objects-usage.ts
> +
In die Anleitung sollten auch noch die Hinweise über die Verwendung bei Subprozessen mit rein.

https://github.com/atlas-engine/ContributionGuidelines/blob/develop/docs/getting_started/bpmn_elements/data_objects.md#dataobjects-and-sub-processes

2020-08-20 07:08 UTC, ElRaptorus approved these changes

2020-08-20 07:10 UTC, SteffenKn commented on src/modules/design/property-panel/indextabs/general/sections/data-objects/data-output-association/data-output-association.scss
> +.information-text {
```suggestion
.information-text {
```

Ich würde hier einen weniger allgemeinen Namen verwenden.
Solch allgemeine CSS Klassennamen können immer gefährlich sein, weil dadurch Inhalte von anderen Komponenten auf einmal anders aussehen können nur weil auf einmal dieser Code geladen wurde.

2020-08-20 09:32 UTC, SteffenKn approved these changes

2020-08-20 09:57 UTC, merged